# Generated by Django 3.0.2 on 2020-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('target', models.URLField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, to='musicae_base.UrlItem')),
            ],
        ),
    ]
