# Generated by Django 3.0.2 on 2020-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
