# Generated by Django 3.0.2 on 2020-02-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0002_urlitem_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlitem',
            name='position',
        ),
    ]
