# Generated by Django 3.0.2 on 2020-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0003_remove_urlitem_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='position',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
