# Generated by Django 3.0.2 on 2020-02-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0004_urlitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='position',
            field=models.IntegerField(),
        ),
    ]
