# Generated by Django 3.0.2 on 2020-02-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0006_auto_20200215_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlitem',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='target',
            field=models.URLField(blank=True, null=True),
        ),
    ]
