# Generated by Django 3.0.2 on 2020-02-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0007_auto_20200215_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
