# Generated by Django 3.0.2 on 2020-02-14 22:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0008_auto_20200215_0013'),
    ]

    operations = [
        migrations.AlterField('UrlItem', 'target', models.CharField(max_length=255,blank=True, null=True))
    ]
