# Generated by Django 3.0.2 on 2020-02-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0010_auto_20200216_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='target',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
