# Generated by Django 3.0.2 on 2020-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_base', '0011_auto_20200216_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='text_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='text_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='text_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
