# Generated by Django 5.2.8 on 2026-03-29 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.TextField(max_length=1000)),
                ('text_bg', models.TextField(max_length=1000, null=True)),
                ('text_en', models.TextField(max_length=1000, null=True)),
                ('text_de', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bg', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('bio_bg', models.TextField(blank=True, null=True)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_de', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_bg', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('currentResearch', models.TextField(blank=True, null=True)),
                ('currentResearch_bg', models.TextField(blank=True, null=True)),
                ('currentResearch_en', models.TextField(blank=True, null=True)),
                ('currentResearch_de', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('short_description_bg', models.TextField(blank=True, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_de', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('image', models.ImageField(blank=True, upload_to='members_img/')),
                ('member', models.BooleanField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('orcid', models.CharField(blank=True, help_text='Enter ORCID in the format 0000-000X-XXXX-XXXX', max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid ORCID in the format 0000-000X-XXXX-XXXX', regex='^\\d{4}-\\d{4}-\\d{4}-[\\dX]{4}$')])),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='pKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('text_bg', models.CharField(max_length=255, null=True, unique=True)),
                ('text_en', models.CharField(max_length=255, null=True, unique=True)),
                ('text_de', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('text_bg', models.CharField(max_length=255, null=True, unique=True)),
                ('text_en', models.CharField(max_length=255, null=True, unique=True)),
                ('text_de', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_bg', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('abstract_bg', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('abstract_de', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('bib_info', models.TextField(blank=True, verbose_name='Bibliographic Info')),
                ('published_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Published Place')),
                ('ptype', models.IntegerField(choices=[(0, 'Монография'), (1, 'Сборник'), (2, 'Дипломен/дисертационен труд'), (3, 'Автореферат'), (4, 'Студия'), (5, 'Статия'), (6, 'Доклад'), (7, 'Учебник'), (8, 'Хабилитация'), (9, 'Онлайн материал'), (10, 'Електронна книга')], default=5, verbose_name='Type')),
                ('publisher_txt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher (Text)')),
                ('journal_txt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Journal (Text)')),
                ('keywords_txt', models.TextField(blank=True, help_text='Enter keywords as a single block of text, separated by commas.', null=True, verbose_name='Keywords (Comma Separated)')),
                ('published_year', models.IntegerField(verbose_name='Year')),
                ('internal', models.BooleanField(default=False, verbose_name='Internal Publication')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('banner', models.ImageField(blank=True, help_text='Image used in the Recent Publications slider.', null=True, upload_to='publication_banners/', verbose_name='Banner image')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='File')),
                ('authors', models.ManyToManyField(related_name='publications', to='musicae_content.person', verbose_name='Authors')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicae_content.ptopic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-published_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Research', max_length=100)),
                ('slug', models.SlugField(default='research', unique=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('menu_order', models.PositiveIntegerField(default=0)),
                ('template', models.CharField(choices=[('alt', 'Research detail'), ('single', 'Research detail — Single column')], default='alt', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='musicae_content.researchpage')),
            ],
            options={
                'verbose_name': 'Research page',
                'verbose_name_plural': 'Research pages',
                'ordering': ['menu_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('title_bg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body (HTML allowed)')),
                ('body_bg', models.TextField(null=True, verbose_name='Body (HTML allowed)')),
                ('body_en', models.TextField(null=True, verbose_name='Body (HTML allowed)')),
                ('body_de', models.TextField(null=True, verbose_name='Body (HTML allowed)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='musicae_content.researchpage')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_sections', to='musicae_content.person')),
            ],
            options={
                'verbose_name': 'Research section',
                'verbose_name_plural': 'Research sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
