# Generated by Django 3.0.2 on 2020-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='pTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.IntegerField(choices=[(0, 'Article'), (1, 'Dissertation'), (2, 'PhD Thesis'), (3, 'Book')])),
                ('published', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('abstract', models.TextField(blank=True)),
                ('fname', models.CharField(max_length=255)),
            ],
        ),
    ]
