# Generated by Django 5.2.8 on 2026-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicae_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="page_range",
            field=models.CharField(
                blank=True,
                help_text="Optional page span, e.g. 45-67.",
                max_length=50,
                null=True,
                verbose_name="Page Range",
            ),
        ),
    ]
