# Generated by Django 3.0.2 on 2020-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('text_en', models.CharField(max_length=250, null=True)),
                ('text_bg', models.CharField(max_length=250, null=True)),
                ('text_de', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='pTopics',
        ),
        migrations.AddField(
            model_name='member',
            name='bio_bg',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bio_de',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bio_en',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='currentResearch',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='currentResearch_bg',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='currentResearch_de',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='currentResearch_en',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='publications',
            field=models.ManyToManyField(blank=True, to='musicae_content.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='topics',
            field=models.ManyToManyField(blank=True, to='musicae_content.pTopic'),
        ),
    ]
