# Generated by Django 5.2.8 on 2026-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0002_publication_page_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-published_year', 'sort_page_start', 'title'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AddField(
            model_name='publication',
            name='container_title',
            field=models.CharField(blank=True, help_text='Book or proceedings title used for chapters and conference papers.', max_length=255, null=True, verbose_name='Container Title'),
        ),
        migrations.AddField(
            model_name='publication',
            name='sort_page_start',
            field=models.PositiveIntegerField(db_index=True, default=999999, editable=False, help_text='Automatically derived from the first page in Page Range.', verbose_name='Sort Page Start'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ptype',
            field=models.IntegerField(choices=[(0, 'Монография'), (1, 'Сборник'), (2, 'Дипломен/дисертационен труд'), (3, 'Автореферат'), (4, 'Студия'), (5, 'Статия'), (6, 'Доклад'), (7, 'Учебник'), (8, 'Хабилитация'), (9, 'Онлайн материал'), (10, 'Електронна книга'), (11, 'Глава')], default=5, verbose_name='Type'),
        ),
    ]
