# Generated by Django 3.0.2 on 2020-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0002_auto_20200216_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='short_description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='short_description_bg',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='short_description_de',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='short_description_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='fname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
