# Generated by Django 5.2.8 on 2026-03-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0003_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_bulgarian',
            field=models.BooleanField(default=False, verbose_name='Is Bulgarian'),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords_txt_bg',
            field=models.TextField(blank=True, help_text='Enter up to 7 keywords separated by commas.', null=True, verbose_name='Keywords (Comma Separated)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords_txt_de',
            field=models.TextField(blank=True, help_text='Enter up to 7 keywords separated by commas.', null=True, verbose_name='Keywords (Comma Separated)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords_txt_en',
            field=models.TextField(blank=True, help_text='Enter up to 7 keywords separated by commas.', null=True, verbose_name='Keywords (Comma Separated)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='keywords_txt',
            field=models.TextField(blank=True, help_text='Enter up to 7 keywords separated by commas.', null=True, verbose_name='Keywords (Comma Separated)'),
        ),
    ]
