# Generated by Django 3.0.2 on 2020-02-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0003_auto_20200226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ptype_bg',
            field=models.IntegerField(choices=[(0, 'Article'), (1, 'Dissertation'), (2, 'PhD Thesis'), (3, 'Book')], null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='ptype_de',
            field=models.IntegerField(choices=[(0, 'Article'), (1, 'Dissertation'), (2, 'PhD Thesis'), (3, 'Book')], null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='ptype_en',
            field=models.IntegerField(choices=[(0, 'Article'), (1, 'Dissertation'), (2, 'PhD Thesis'), (3, 'Book')], null=True),
        ),
    ]
