# Generated by Codex on 2026-03-29

from django.db import migrations


def backfill_bulgarian_flags(apps, schema_editor):
    Publication = apps.get_model("musicae_content", "Publication")
    for publication in Publication.objects.all():
        language = (publication.language or "").strip().lower()
        is_bg = language.startswith("bg")
        updates = {}
        if publication.is_bulgarian != is_bg:
            updates["is_bulgarian"] = is_bg
        if hasattr(publication, "keywords_txt_bg") and not (publication.keywords_txt_bg or "").strip():
            if (publication.keywords_txt or "").strip():
                updates["keywords_txt_bg"] = publication.keywords_txt
        if updates:
            Publication.objects.filter(pk=publication.pk).update(**updates)


class Migration(migrations.Migration):
    dependencies = [
        ("musicae_content", "0004_publication_is_bulgarian_publication_keywords_txt_bg_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_bulgarian_flags, migrations.RunPython.noop),
    ]
