# Generated by Django 3.0.2 on 2020-02-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0004_auto_20200229_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='ptype_bg',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='ptype_de',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='ptype_en',
        ),
    ]
