# Generated by Django 3.0.2 on 2020-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0005_auto_20200229_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=400)),
                ('time_and_place', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['-start_date', 'end_date'],
                'get_latest_by': '-start_date',
            },
        ),
    ]
