# Generated by Django 3.0.2 on 2020-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0006_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='description_bg',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='description_de',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='description_en',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='time_and_place_bg',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='time_and_place_de',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='time_and_place_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_bg',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_de',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_en',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
