# Generated by Django 3.0.2 on 2020-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0007_auto_20200301_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='fname',
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(default=1, upload_to='publications/'),
            preserve_default=False,
        ),
    ]
