# Generated by Django 3.0.2 on 2020-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicae_content', '0008_auto_20200301_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=400)),
                ('title_bg', models.CharField(max_length=400, null=True)),
                ('title_en', models.CharField(max_length=400, null=True)),
                ('title_de', models.CharField(max_length=400, null=True)),
                ('image', models.FileField(upload_to='news_img/')),
                ('content', models.TextField(max_length=5000)),
                ('content_bg', models.TextField(max_length=5000, null=True)),
                ('content_en', models.TextField(max_length=5000, null=True)),
                ('content_de', models.TextField(max_length=5000, null=True)),
            ],
            options={
                'ordering': ['-added'],
                'get_latest_by': '-added',
            },
        ),
    ]
